# Generated by Django 3.1.4 on 2021-07-01 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tms', '0002_auto_20210620_1458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testexec',
            name='testnode',
        ),
        migrations.AddField(
            model_name='testresult',
            name='testnode',
            field=models.CharField(default='TEST-1', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='release',
            name='rel_type',
            field=models.CharField(default='unknown', max_length=20),
        ),
    ]
