# Generated by Django 3.1.4 on 2021-07-11 16:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tms', '0003_auto_20210702_0015'),
    ]

    operations = [
        migrations.AddField(
            model_name='testexec',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 11, 16, 44, 26, 514524, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
